### PR TITLE
VS compilation fixes

### PR DESCRIPTION
**Pull request by elasota**
Changing some calls to use Microsoft CRT versions, replacing C dynamic arrays with alloca/malloc.

### CODE REVIEW

**Comment by sfiera** [comment]
Apparently upstream has already dropped variable-length arrays: https://github.com/libsndfile/libsndfile/commit/ba352a1ce7dc8393621edde214367a789035c721
So I’d like to have a go at updating to 1.0.31 before merging this.

**Comment by sfiera** [comment]
I updated to 1.0.31. I noticed that some of the code you edited was replaced by:
```c
/* Huge chunk of code removed here because it had egregious errors that were
** not detected by either the compiler or the tests. It was found when updating
** the way psf_binheader_writef works.
*/
```
So that’s nice.

**Comment by elasota** [comment]
Updated just the config for now, will give this another go in a bit

**Comment by elasota** [comment]
This should be the last required PR to get the antares submodules compiling.

**Comment by sfiera** [comment]
Do you mean this is ready to merge?

**Comment by elasota** [comment]
Yes, I took out all of the changes to libsndfile, this only updates config.h now.

**Pull request merged**
